In [2]:
## install pandas 

!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# import pandas

import pandas as pd

In [4]:
## series in pandas 

# 1->from lists

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))


# 2-> from dictionary 


data={'a':1,'b':2,'c':3}
series2=pd.Series(data)
print(series2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64

In [5]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
series = pd.Series(data, index=index)
print(series)

a    10
b    20
c    30
dtype: int64

In [6]:
## data frame in python 


# 1->create a data frame from a dictionary


data={
    'name':["akash","aman","ram"],
    'age':[10,20,30],
    'city':["banglore","noida","delhi"]

}



print(pd.DataFrame(data))

    name  age      city
0  akash   10  banglore
1   aman   20     noida
2    ram   30     delhi

In [7]:
## create a dataframe from a list of dictionaries 

people = [
    {'name': 'Alice', 'age': 30, 'city': 'New York'},
    {'name': 'Bob', 'age': 25, 'city': 'Los Angeles'},
    {'name': 'Charlie', 'age': 35, 'city': 'Chicago'},
    {'name': 'David', 'age': 28, 'city': 'Miami'},
    {'name': 'Eva', 'age': 22, 'city': 'San Francisco'}
]



people_df=pd.DataFrame(people)

print(people_df)

      name  age           city
0    Alice   30       New York
1      Bob   25    Los Angeles
2  Charlie   35        Chicago
3    David   28          Miami
4      Eva   22  San Francisco

In [8]:
## read a csv file using pandas 

iris_dataset =pd.read_csv("iris.csv")
iris_dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [9]:
## see top 5 row 

print(iris_dataset.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
## see the last 5 row 

print(iris_dataset.tail())

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

In [11]:
## see the first 10 row 

print(iris_dataset.head(10))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [12]:
## accessing data from the dataframe 
print(people_df['name'])

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: name, dtype: object

In [ ]:
## pick first row 

print(people_df.loc[0])
print("hii")
print(people_df.iloc[0])

name      Alice
salary    10000
Name: 0, dtype: object
hii
name      Alice
salary    10000
Name: 0, dtype: object

In [43]:
## accessing a specified element 

## means get the age of the element at index 1

print(people_df.at[2,'city'])

KeyError: 'city'

In [15]:
## using iat

people_df.iat[2,2]

'Chicago'

In [16]:
## add a new column 

people_df['salary']=[10000,20000,30000,40000,50000]
people_df

      name  age           city  salary
0    Alice   30       New York   10000
1      Bob   25    Los Angeles   20000
2  Charlie   35        Chicago   30000
3    David   28          Miami   40000
4      Eva   22  San Francisco   50000

In [ ]:
## remove a column 

people_df.drop(columns=['salary'],axis=1)

      name  age           city
0    Alice   30       New York
1      Bob   25    Los Angeles
2  Charlie   35        Chicago
3    David   28          Miami
4      Eva   22  San Francisco

In [18]:
people_df

      name  age           city  salary
0    Alice   30       New York   10000
1      Bob   25    Los Angeles   20000
2  Charlie   35        Chicago   30000
3    David   28          Miami   40000
4      Eva   22  San Francisco   50000

In [19]:
people_df

      name  age           city  salary
0    Alice   30       New York   10000
1      Bob   25    Los Angeles   20000
2  Charlie   35        Chicago   30000
3    David   28          Miami   40000
4      Eva   22  San Francisco   50000

In [20]:
## method 1->to permanently delete a column 

people_df=people_df.drop(columns=['age'],axis=1)
people_df

      name           city  salary
0    Alice       New York   10000
1      Bob    Los Angeles   20000
2  Charlie        Chicago   30000
3    David          Miami   40000
4      Eva  San Francisco   50000

In [21]:
## method 2-> using inplace 
people_df.drop(columns=['city'],axis=1,inplace=True)

In [22]:
people_df

      name  salary
0    Alice   10000
1      Bob   20000
2  Charlie   30000
3    David   40000
4      Eva   50000

In [23]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [30, 25, 35],
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'salary': [70000, 80000, 90000]
}

data=pd.DataFrame(data)
print(data)

      name  age         city  salary
0    Alice   30     New York   70000
1      Bob   25  Los Angeles   80000
2  Charlie   35      Chicago   90000

In [24]:
## we want to increase everyones age by 1 

data['age']=data['age']+1

In [25]:
data

      name  age         city  salary
0    Alice   31     New York   70000
1      Bob   26  Los Angeles   80000
2  Charlie   36      Chicago   90000

In [26]:
## drop a row 

data.drop(0,inplace=True)

In [27]:
data

      name  age         city  salary
1      Bob   26  Los Angeles   80000
2  Charlie   36      Chicago   90000

In [28]:
# ATTRIBUTES 


print("DataTypes of attributes:/n",iris_dataset.dtypes)

DataTypes of attributes:/n Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [29]:
## statical summary of the data 


print("statical summary :\n" ,iris_dataset.describe())

statical summary :
                Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [30]:

## see the first five row of iris data set 

iris_dataset=pd.read_csv("iris.csv")
iris_dataset.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
## check the last five records 

iris_dataset.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [32]:
## Handling Missing values->method to check no of missing values in any column 


iris_dataset.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [33]:
## read the sales data

df = pd.read_csv("sales_data_sample.csv", encoding='latin1')
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [34]:
## find misiing values 


df.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [35]:
df_filled=df.fillna(0)

In [36]:
df_filled

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,0,NYC,NY,10022,USA,0,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,0,Reims,0,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,0,Paris,0,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,0,Pasadena,CA,90003,USA,0,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,0,San Francisco,CA,0,USA,0,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",0,Madrid,0,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,0,Oulu,0,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",0,Madrid,0,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,0,Toulouse,0,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,0,Boston,MA,51003,USA,0,Yoshido,Juri,Medium

In [37]:
df_filled.isnull().any()

ORDERNUMBER         False
QUANTITYORDERED     False
PRICEEACH           False
ORDERLINENUMBER     False
SALES               False
ORDERDATE           False
STATUS              False
QTR_ID              False
MONTH_ID            False
YEAR_ID             False
PRODUCTLINE         False
MSRP                False
PRODUCTCODE         False
CUSTOMERNAME        False
PHONE               False
ADDRESSLINE1        False
ADDRESSLINE2        False
CITY                False
STATE               False
POSTALCODE          False
COUNTRY             False
TERRITORY           False
CONTACTLASTNAME     False
CONTACTFIRSTNAME    False
DEALSIZE            False
dtype: bool

In [38]:
## read the sales data again 

df = pd.read_csv("sales_data_sample.csv", encoding='latin1')
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [39]:
## check missing values 

df.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [40]:
## fill the missing values with the mean of the column
# note->this is the way we are getting error because it is not a numerical value 
#  

df['POSTALCODE']=df['POSTALCODE'].fillna(df['POSTALCODE'].mean())

TypeError: can only concatenate str (not "int") to str

In [ ]:
df['POSTALCODE'].dtype

dtype('O')

In [ ]:
iris_dataset.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
## renaming of columns 

iris_dataset.rename(columns={'SepalLengthCm':"sepal"},inplace=True)

In [ ]:
iris_dataset.head()

   Id  sepal  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1    5.1           3.5            1.4           0.2  Iris-setosa
1   2    4.9           3.0            1.4           0.2  Iris-setosa
2   3    4.7           3.2            1.3           0.2  Iris-setosa
3   4    4.6           3.1            1.5           0.2  Iris-setosa
4   5    5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris_dataset.dtypes

Id                 int64
sepal            float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
## chnages datatypes of columns 


iris_dataset['PetalWidthCm']=iris_dataset['PetalWidthCm'].astype(int)

In [ ]:
iris_dataset.dtypes

Id                 int64
sepal            float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm       int64
Species           object
dtype: object

In [ ]:
iris_dataset.head()

   Id  sepal  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1    5.1           3.5            1.4             0  Iris-setosa
1   2    4.9           3.0            1.4             0  Iris-setosa
2   3    4.7           3.2            1.3             0  Iris-setosa
3   4    4.6           3.1            1.5             0  Iris-setosa
4   5    5.0           3.6            1.4             0  Iris-setosa

In [ ]:
## want to apply any function on a column 

## lets multiply petal length by 2 


iris_dataset['PetalLengthCm']=iris_dataset['PetalLengthCm'].apply(lambda x:x*2)

In [ ]:
iris_dataset.head()

   Id  sepal  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1    5.1           3.5            2.8             0  Iris-setosa
1   2    4.9           3.0            2.8             0  Iris-setosa
2   3    4.7           3.2            2.6             0  Iris-setosa
3   4    4.6           3.1            3.0             0  Iris-setosa
4   5    5.0           3.6            2.8             0  Iris-setosa

In [ ]:
mean_sepal = df.groupby('Species')[['sepal']].mean()

KeyError: 'Species'

In [ ]:
iris_dataset.dtypes

Id                 int64
sepal            float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm       int64
Species           object
dtype: object

In [ ]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
average_order=df.groupby('YEAR_ID')['QUANTITYORDERED'].mean()
print(average_order)

YEAR_ID
2003    34.612000
2004    34.813383
2005    36.884937
Name: QUANTITYORDERED, dtype: float64

In [ ]:
sum_order=df.groupby(['YEAR_ID','MONTH_ID'])['QUANTITYORDERED'].sum()
print(sum_order)

YEAR_ID  MONTH_ID
2003     1            1357
         2            1449
         3            1755
         4            1993
         5            2017
         6            1649
         7            1725
         8            1974
         9            2510
         10           5515
         11          10179
         12           2489
2004     1            3245
         2            3061
         3            1978
         4            2077
         5            2618
         6            2971
         7            3174
         8            4564
         9            3171
         10           5483
         11          10678
         12           3804
2005     1            3395
         2            3393
         3            3852
         4            2634
         5            4357
Name: QUANTITYORDERED, dtype: int64

In [ ]:
## multiple aggregate function 

df_agg=df.groupby('YEAR_ID')['QUANTITYORDERED'].agg(['mean','median','sum','count'])
df_agg

              mean  median    sum  count
YEAR_ID
2003     34.612000    34.0  34612   1000
2004     34.813383    35.0  46824   1345
2005     36.884937    36.0  17631    478

In [ ]:
df1=pd.DataFrame({'key':['A','B','C'],'value':[1,2,3]})
df2=pd.DataFrame({'key':['A','D','E'],'value':[3,5,6]})

df3 = pd.merge(df1, df2, on="key", how="inner")
print(df3)

  key  value_x  value_y
0   A        1        3

In [ ]:

df1=pd.DataFrame({'key':['A','B','C'],'value':[1,2,3]})
df2=pd.DataFrame({'key':['A','D','E'],'value':[3,5,6]})

df3 = pd.merge(df1, df2, on="key", how="outer")
print(df3)

  key  value_x  value_y
0   A      1.0      3.0
1   B      2.0      NaN
2   C      3.0      NaN
3   D      NaN      5.0
4   E      NaN      6.0

In [ ]:
df1=pd.DataFrame({'key':['A','B','C'],'value':[1,2,3]})
df2=pd.DataFrame({'key':['A','D','E'],'value':[3,5,6]})

df3 = pd.merge(df1, df2, on="key", how="left")
print(df3)

  key  value_x  value_y
0   A        1      3.0
1   B        2      NaN
2   C        3      NaN

In [ ]:
df1=pd.DataFrame({'key':['A','B','C'],'value':[1,2,3]})
df2=pd.DataFrame({'key':['A','D','E'],'value':[3,5,6]})

df3 = pd.merge(df1, df2, on="key", how="right")
print(df3)

  key  value_x  value_y
0   A      1.0        3
1   D      NaN        5
2   E      NaN        6

## Reading data from different source

In [ ]:
import pandas as pd
from io import StringIO
import json
data={
    "name":"akash chandra",
    "email":"akashc.ug23.cs@nitp.ac.in",
    "job profile":[{"title1":"web developer","title2":"machine learning"}]
}

df=pd.read_json(StringIO(json.dumps(data)))
df

,name,email,job profile
0,akash chandra,akashc.ug23.cs@nitp.ac.in,"{'title1': 'web developer', 'title2': 'machine..."

In [ ]:
## again convert it into a json 

df.to_json()

'{"name":{"0":"akash chandra"},"email":{"0":"akashc.ug23.cs@nitp.ac.in"},"job profile":{"0":{"title1":"web developer","title2":"machine learning"}}}'

In [ ]:
df.to_json(orient="index")

'{"0":{"name":"akash chandra","email":"akashc.ug23.cs@nitp.ac.in","job profile":{"title1":"web developer","title2":"machine learning"}}}'

In [ ]:
df.to_json(orient="records")

'[{"name":"akash chandra","email":"akashc.ug23.cs@nitp.ac.in","job profile":{"title1":"web developer","title2":"machine learning"}}]'

In [ ]:
## read data from a url 

df=pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv")

In [ ]:
df.head()

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

In [ ]:
!pip install lxml

Collecting lxml
  Downloading lxml-5.4.0-cp312-cp312-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-5.4.0-cp312-cp312-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB 393.8 kB/s eta 0:00:10
   - -------------------------------------- 0.1/3.8 MB 819.2 kB/s eta 0:00:05
   -- ------------------------------------- 0.2/3.8 MB 1.4 MB/s eta 0:00:03
   ----- ---------------------------------- 0.5/3.8 MB 2.3 MB/s eta 0:00:02
   ----------- ---------------------------- 1.1/3.8 MB 3.9 MB/s eta 0:00:01
   ----------------- ---------------------- 1.7/3.8 MB 5.4 MB/s eta 0:00:01
   --------------------------- ------------ 2.6/3.8 MB 7.3 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 8.4 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-5.4.0

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
## read html with pandas 

df=pd.read_html("https://www.fdic.gov/bank-failures/failed-bank-list")
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
1,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,"First Bank & Trust Co., Duncan, OK","October 18, 2024",10547
2,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
3,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
4,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
5,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
6,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
7,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
8,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
9,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537

In [ ]:
! pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (2.2.3)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from pandas) (2025.2)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp\desktop\summer break machine learning\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ------ -------------------------------- 41.0/250.9 kB 393.8 kB/s eta 0:00:01
   -------------- ------------------------ 92.2/250.9 kB 655.4 kB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.3 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
df=pd.read_excel("excel.xlsx",engine="openpyxl")

In [ ]:
df

      NAME  AGE
0    AKASH   20
1     JACK   32
2  ABHINAV   27
3   MRINAL   30

In [ ]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
df.to_pickle("df_excel")

In [ ]:
pd.read_pickle("df_excel")

      NAME  AGE
0    AKASH   20
1     JACK   32
2  ABHINAV   27
3   MRINAL   30