In [1]:
import pandas as pd

In [5]:
df=pd.read_excel("flight-price.xlsx")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [6]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [7]:
## get basic info about data 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [8]:
##check statical data
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

## Handle Date of Journey

In [12]:
## handle date of journey

## our model will not understand the data so we break the date into three parts day ,month and year

df['date']=df['Date_of_Journey'].str.split('/').str[0]
df['month']=df['Date_of_Journey'].str.split('/').str[1]
df['year']=df['Date_of_Journey'].str.split('/').str[2]

In [13]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  date             10683 non-null  object
 12  month            10683 non-null  object
 13  year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [15]:
df['date']=df['date'].astype('int')
df['month']=df['month'].astype('int')
df['year']=df['year'].astype('int')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  date             10683 non-null  int64
 12  month            10683 non-null  int64
 13  year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [18]:
## drop date of journey column
df.drop(columns=["Date_of_Journey"],axis=1,inplace=True)

In [19]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

## Handle Arrival Time

In [24]:
# df['Arrival_Time'].str.split(':').str[1].str.split(" ").str[0]

df['arrival_hour']=df['Arrival_Time'].str.split(":").str[0]
df["arrival_minute"]=df['Arrival_Time'].str.split(":").str[1].str.split(" ").str[0]

In [25]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  date             10683 non-null  int64
 11  month            10683 non-null  int64
 12  year             10683 non-null  int64
 13  arrival_hour     10683 non-null  object
 14  arrival_minute   10683 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.2+ MB

In [27]:
df['arrival_hour']=df['arrival_hour'].astype('int')
df['arrival_minute']=df['arrival_minute'].astype('int')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  date             10683 non-null  int64
 11  month            10683 non-null  int64
 12  year             10683 non-null  int64
 13  arrival_hour     10683 non-null  int64
 14  arrival_minute   10683 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [29]:
## drop arrival_time 
df.drop(columns=["Arrival_Time"],axis=1,inplace=True)

In [30]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35

## Handle Departure Time

In [31]:
df["departure_hour"]=df["Dep_Time"].str.split(":").str[0]
df["departure_minute"]=df["Dep_Time"].str.split(":").str[1]

In [32]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,departure_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15,05,50

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  object
 1   Source            10683 non-null  object
 2   Destination       10683 non-null  object
 3   Route             10682 non-null  object
 4   Dep_Time          10683 non-null  object
 5   Duration          10683 non-null  object
 6   Total_Stops       10682 non-null  object
 7   Additional_Info   10683 non-null  object
 8   Price             10683 non-null  int64
 9   date              10683 non-null  int64
 10  month             10683 non-null  int64
 11  year              10683 non-null  int64
 12  arrival_hour      10683 non-null  int64
 13  arrival_minute    10683 non-null  int64
 14  departure_hour    10683 non-null  object
 15  departure_minute  10683 non-null  object
dtypes: int64(6), object(10)
memory usage: 1.3+ MB

In [34]:
df["departure_hour"]=df["departure_hour"].astype('int')
df["departure_minute"]=df["departure_minute"].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  object
 1   Source            10683 non-null  object
 2   Destination       10683 non-null  object
 3   Route             10682 non-null  object
 4   Dep_Time          10683 non-null  object
 5   Duration          10683 non-null  object
 6   Total_Stops       10682 non-null  object
 7   Additional_Info   10683 non-null  object
 8   Price             10683 non-null  int64
 9   date              10683 non-null  int64
 10  month             10683 non-null  int64
 11  year              10683 non-null  int64
 12  arrival_hour      10683 non-null  int64
 13  arrival_minute    10683 non-null  int64
 14  departure_hour    10683 non-null  int64
 15  departure_minute  10683 non-null  int64
dtypes: int64(8), object(8)
memory usage: 1.3+ MB

In [36]:
df.drop(columns=["Dep_Time"],axis=1,inplace=True)

In [37]:
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,departure_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50

## Handle Total_Stops

In [38]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [39]:
df['Total_Stops'].isnull().sum()

np.int64(1)

In [40]:
df.isnull().sum()

Airline             0
Source              0
Destination         0
Route               1
Duration            0
Total_Stops         1
Additional_Info     0
Price               0
date                0
month               0
year                0
arrival_hour        0
arrival_minute      0
departure_hour      0
departure_minute    0
dtype: int64

In [42]:
## since we have only 2 rows with null value drop these 

df.dropna(inplace=True)

In [43]:
df.isnull().sum()

Airline             0
Source              0
Destination         0
Route               0
Duration            0
Total_Stops         0
Additional_Info     0
Price               0
date                0
month               0
year                0
arrival_hour        0
arrival_minute      0
departure_hour      0
departure_minute    0
dtype: int64

In [46]:
## use ordinal encoder to encode the Total_stops

from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[["non-stop","1 stop","2 stops","3 stops","4 stops"]])
encoded_total_stops=encoder.fit_transform(df[["Total_Stops"]])

In [47]:
encoded_total_stops

array([[0.],
       [2.],
       [2.],
       ...,
       [0.],
       [0.],
       [2.]], shape=(10682, 1))

In [49]:
new_df=pd.DataFrame(encoded_total_stops,columns=["encoded_total_stops"])

In [50]:
new_df

       encoded_total_stops
0                      0.0
1                      2.0
2                      2.0
3                      1.0
4                      1.0
...                    ...
10677                  0.0
10678                  0.0
10679                  0.0
10680                  0.0
10681                  2.0

[10682 rows x 1 columns]

In [52]:
df=pd.concat([df,new_df],axis=1)

In [53]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,departure_minute,encoded_total_stops
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,0.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,2.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,2.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,1.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,1.0

In [54]:
df.drop(columns=["Total_Stops"],axis=1,inplace=True)

In [55]:
df.head()

,Airline,Source,Destination,Route,Duration,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,departure_minute,encoded_total_stops
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,No info,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,0.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,No info,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,2.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,No info,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,2.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,No info,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,1.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,No info,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,1.0

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10683 entries, 0 to 9039
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Airline              10682 non-null  object
 1   Source               10682 non-null  object
 2   Destination          10682 non-null  object
 3   Route                10682 non-null  object
 4   Duration             10682 non-null  object
 5   Additional_Info      10682 non-null  object
 6   Price                10682 non-null  float64
 7   date                 10682 non-null  float64
 8   month                10682 non-null  float64
 9   year                 10682 non-null  float64
 10  arrival_hour         10682 non-null  float64
 11  arrival_minute       10682 non-null  float64
 12  departure_hour       10682 non-null  float64
 13  departure_minute     10682 non-null  float64
 14  encoded_total_stops  10682 non-null  float64
dtypes: float64(9), object(6)
memory usage: 1.3+ MB

## Handle Duration

In [68]:
df["Duration_hour"] = 0
df["Duration_min"] = 0

df.loc[df["Duration"].str.contains("h", na=False), "Duration_hour"] = (
    df["Duration"].str.extract(r'(\d+)h')[0].fillna(0).astype(int)
)

df.loc[df["Duration"].str.contains("m", na=False), "Duration_min"] = (
    df["Duration"].str.extract(r'(\d+)m')[0].fillna(0).astype(int)
)

In [70]:
df.head()

,Airline,Source,Destination,Route,Duration,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,departure_minute,encoded_total_stops,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h,No info,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,0.0,2,0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h,No info,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,2.0,7,0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,No info,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,2.0,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h,No info,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,1.0,5,0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h,No info,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,1.0,4,0

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10683 entries, 0 to 9039
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Airline              10682 non-null  object
 1   Source               10682 non-null  object
 2   Destination          10682 non-null  object
 3   Route                10682 non-null  object
 4   Duration             10682 non-null  object
 5   Additional_Info      10682 non-null  object
 6   Price                10682 non-null  float64
 7   date                 10682 non-null  float64
 8   month                10682 non-null  float64
 9   year                 10682 non-null  float64
 10  arrival_hour         10682 non-null  float64
 11  arrival_minute       10682 non-null  float64
 12  departure_hour       10682 non-null  float64
 13  departure_minute     10682 non-null  float64
 14  encoded_total_stops  10682 non-null  float64
 15  Duration_hour        10683 non-null  int64
 16  Duration_min         10683 non-null  int64
dtypes: float64(9), int64(2), object(6)
memory usage: 1.7+ MB

In [72]:
## drop duration column
df.drop(columns=["Duration"],axis=1,inplace =True)

In [73]:
df.head(2)

,Airline,Source,Destination,Route,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,departure_minute,encoded_total_stops,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,No info,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,0.0,2,0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,No info,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,2.0,7,0

## Handle Airline

In [74]:
df["Airline"].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet', nan], dtype=object)

In [75]:
from sklearn.preprocessing import   OneHotEncoder

In [83]:
encoder=OneHotEncoder()
encoded_airline=encoder.fit_transform(df[["Airline"]]).toarray()

In [85]:
## create dataframe 

df_new=pd.DataFrame(encoded_airline,columns=encoder.get_feature_names_out())

In [86]:
df=pd.concat([df,df_new],axis=1)

In [87]:
df.head()

,Airline,Source,Destination,Route,Additional_Info,Price,date,month,year,arrival_hour,...,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy,Airline_nan
0,IndiGo,Banglore,New Delhi,BLR → DEL,No info,3897.0,24.0,3.0,2019.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,No info,7662.0,1.0,5.0,2019.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,No info,13882.0,9.0,6.0,2019.0,4.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,No info,6218.0,12.0,5.0,2019.0,23.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,No info,13302.0,1.0,3.0,2019.0,21.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [88]:
df.drop(columns=["Airline"],axis=1,inplace=True)

In [89]:
df.head()

,Source,Destination,Route,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,...,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy,Airline_nan
0,Banglore,New Delhi,BLR → DEL,No info,3897.0,24.0,3.0,2019.0,1.0,10.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Kolkata,Banglore,CCU → IXR → BBI → BLR,No info,7662.0,1.0,5.0,2019.0,13.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Delhi,Cochin,DEL → LKO → BOM → COK,No info,13882.0,9.0,6.0,2019.0,4.0,25.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Kolkata,Banglore,CCU → NAG → BLR,No info,6218.0,12.0,5.0,2019.0,23.0,30.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Banglore,New Delhi,BLR → NAG → DEL,No info,13302.0,1.0,3.0,2019.0,21.0,35.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10683 entries, 0 to 9039
Data columns (total 28 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Source                                     10682 non-null  object
 1   Destination                                10682 non-null  object
 2   Route                                      10682 non-null  object
 3   Additional_Info                            10682 non-null  object
 4   Price                                      10682 non-null  float64
 5   date                                       10682 non-null  float64
 6   month                                      10682 non-null  float64
 7   year                                       10682 non-null  float64
 8   arrival_hour                               10682 non-null  float64
 9   arrival_minute                             10682 non-null  float64
 10  departure_hour                             10682 non-null  float64
 11  departure_minute                           10682 non-null  float64
 12  encoded_total_stops                        10682 non-null  float64
 13  Duration_hour                              10683 non-null  int64
 14  Duration_min                               10683 non-null  int64
 15  Airline_Air Asia                           10683 non-null  float64
 16  Airline_Air India                          10683 non-null  float64
 17  Airline_GoAir                              10683 non-null  float64
 18  Airline_IndiGo                             10683 non-null  float64
 19  Airline_Jet Airways                        10683 non-null  float64
 20  Airline_Jet Airways Business               10683 non-null  float64
 21  Airline_Multiple carriers                  10683 non-null  float64
 22  Airline_Multiple carriers Premium economy  10683 non-null  float64
 23  Airline_SpiceJet                           10683 non-null  float64
 24  Airline_Trujet                             10683 non-null  float64
 25  Airline_Vistara                            10683 non-null  float64
 26  Airline_Vistara Premium economy            10683 non-null  float64
 27  Airline_nan                                10683 non-null  float64
dtypes: float64(22), int64(2), object(4)
memory usage: 2.4+ MB

## Handle Source

In [95]:
df["Source"].fillna(df["Source"].mode()[0],inplace=True)

In [96]:
df["Source"].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [97]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoded_source=encoder.fit_transform(df[["Source"]]).toarray()
new_df=pd.DataFrame(encoded_source,columns=encoder.get_feature_names_out())
df=pd.concat([df,new_df],axis=1)
df.drop(columns=["Source"],axis=1,inplace=True)

In [98]:
df.head()

,Destination,Route,Additional_Info,Price,date,month,year,arrival_hour,arrival_minute,departure_hour,...,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy,Airline_nan,Source_Banglore,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai
0,New Delhi,BLR → DEL,No info,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,Banglore,CCU → IXR → BBI → BLR,No info,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Cochin,DEL → LKO → BOM → COK,No info,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,Banglore,CCU → NAG → BLR,No info,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,New Delhi,BLR → NAG → DEL,No info,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [99]:
df["Additional_Info"].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover', nan], dtype=object)