In [1]:

import pandas as pd

# One Hot Encoding -> used for columns having more than two categories

In [2]:
df=pd.DataFrame({
    'colors':["red","green","blue","red","blue"]
})

df.head()

  colors
0    red
1  green
2   blue
3    red
4   blue

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['colors']]).toarray()

In [5]:
final_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [6]:
final_df

   colors_blue  colors_green  colors_red
0          0.0           0.0         1.0
1          0.0           1.0         0.0
2          1.0           0.0         0.0
3          0.0           0.0         1.0
4          1.0           0.0         0.0

In [7]:
pd.concat([final_df,df],axis=1)

   colors_blue  colors_green  colors_red colors
0          0.0           0.0         1.0    red
1          0.0           1.0         0.0  green
2          1.0           0.0         0.0   blue
3          0.0           0.0         1.0    red
4          1.0           0.0         0.0   blue

In [8]:
## practical with dataset

import seaborn as sns 

df=sns.load_dataset('tips')

In [9]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [11]:
encoded_sex=encoder.fit_transform(df[['sex']]).toarray()

encoded_sex_df=pd.DataFrame(encoded_sex,columns=encoder.get_feature_names_out())
encoded_sex_df.head()

   sex_Female  sex_Male
0         1.0       0.0
1         0.0       1.0
2         0.0       1.0
3         0.0       1.0
4         1.0       0.0

In [12]:
## now drop original sex column 

df.drop(columns=["sex"],axis=1,inplace=True)

In [13]:
pd.concat([df,encoded_sex_df],axis=1)

     total_bill   tip smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61     No   Sun  Dinner     4         1.0       0.0
..          ...   ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00     No  Thur  Dinner     2         1.0       0.0

[244 rows x 8 columns]

# Label Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
lbl_encoder=LabelEncoder()

In [16]:
encoded_day=lbl_encoder.fit_transform(df[["day"]])

c:\Users\t6201\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [17]:
encoded_day_df=pd.DataFrame(encoded_day,columns=["day"])

In [18]:
df.drop(columns=["day"],inplace=True)

In [19]:
final_df=pd.concat([df,encoded_day_df],axis=1)

In [20]:
final_df.head

<bound method NDFrame.head of      total_bill   tip smoker    time  size  day
0         16.99  1.01     No  Dinner     2    2
1         10.34  1.66     No  Dinner     3    2
2         21.01  3.50     No  Dinner     3    2
3         23.68  3.31     No  Dinner     2    2
4         24.59  3.61     No  Dinner     4    2
..          ...   ...    ...     ...   ...  ...
239       29.03  5.92     No  Dinner     3    1
240       27.18  2.00    Yes  Dinner     2    1
241       22.67  2.00    Yes  Dinner     2    1
242       17.82  1.75     No  Dinner     2    1
243       18.78  3.00     No  Dinner     2    3

[244 rows x 6 columns]>

# Ordinal Encoding

In [21]:
# ## example->
# High school->1
# college->2
# graduate->3
# post_graduate->4

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
df=pd.DataFrame({
    'size':["small","medium","large","medium","small","large"]
})

In [24]:
## create an instance of ordinal encoder

encoder=OrdinalEncoder(categories=[["small","medium","large"]])

In [25]:
encoded_size=encoder.fit_transform(df[['size']])

In [26]:
encoded_size_df=pd.DataFrame(encoded_size,columns=["encoded_size"])

In [27]:
final_df=pd.concat([df,encoded_size_df],axis=1)

In [28]:
final_df

     size  encoded_size
0   small           0.0
1  medium           1.0
2   large           2.0
3  medium           1.0
4   small           0.0
5   large           2.0

# Target Guided Ordinal Encoding

In [29]:
## THEORY:-
## in the target guided ordinal encoding we replace each category in the categorical variable with the numerical value based on mean or median of the target variable for each category

In [30]:
import pandas as pd
df=pd.DataFrame(
    {
        'city':["new york","london","paris","tokyo","new york","paris"],
        'price':[200,150,300,250,180,320]
    }
)

In [31]:
city_mean=df.groupby('city')["price"].mean().to_dict()

In [32]:
df['city_Encoded']=df['city'].map(city_mean)

In [33]:
df

       city  price  city_Encoded
0  new york    200         190.0
1    london    150         150.0
2     paris    300         310.0
3     tokyo    250         250.0
4  new york    180         190.0
5     paris    320         310.0