# 📊 Working with CSV Files in Pandas - Complete Guide

In [ ]:

import pandas as pd

## 📂 2. Loading Local CSV Files

### 🎯 Learning Objective:
Master the fundamentals of reading CSV files from your local file system.

### 📋 Key Concepts:
- **Local File Paths**: Understanding relative vs absolute paths
- **File Location**: Working directory and file accessibility
- **Basic read_csv()**: The most common pandas operation

### 💡 Best Practice:
Always verify your working directory and file location before attempting to read files.

### 🔧 Implementation:

In [10]:
# Read the local CSV file into a pandas DataFrame
df = pd.read_csv('aug_train.csv')

# Display the DataFrame
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

## 🌐 3. Reading CSV from URLs

### 🎯 Learning Objective:
Learn to fetch and load CSV data directly from web URLs for remote data access.

### 📋 Key Concepts:
- **HTTP Requests**: Making web requests to fetch data
- **User-Agent Headers**: Identifying your request to avoid blocking
- **StringIO**: Converting text data to file-like objects
- **Remote Data Access**: Accessing datasets hosted online

### 💡 Why This Matters:
Many datasets are hosted online, and direct URL reading enables:
- ✅ **Real-time Data**: Access to live, updated datasets
- ✅ **Collaboration**: Shared access to common datasets
- ✅ **Reproducibility**: Consistent data source across environments

### 🔧 Implementation:

In [ ]:
# Import required libraries for web requests
import requests
from io import StringIO

# Define the URL and headers
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}


# Make the HTTP request
req = requests.get(url, headers=headers)

# Convert the response text to a file-like object
data = StringIO(req.text)

# Read the CSV data
df_countries = pd.read_csv(data)

# Display the DataFrame
df_countries.head()

🌐 Fetching data from URL...

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

## 🔧 4. Separator Parameter (sep)

### 🎯 Learning Objective:
Master the `sep` parameter to handle different file delimiters beyond commas.

### 📋 Key Concepts:
- **Delimiters**: Characters that separate values in files
- **TSV Files**: Tab-Separated Values (using `\t`)
- **Custom Separators**: Pipe (`|`), semicolon (`;`), or other characters
- **File Format Recognition**: Identifying the correct separator

### 💡 Common Separators:
- `,` - **Comma** (CSV default)
- `\t` - **Tab** (TSV files)
- `;` - **Semicolon** (European CSV format)
- `|` - **Pipe** (Database exports)

### 🔧 Implementation:

In [13]:
# Reading a TSV (Tab-Separated Values) file
# The `sep='\t'` parameter tells pandas to use tabs as delimiters instead of commas


# Define meaningful column names for the movie dataset
column_names = ['sno', 'name', 'release_year', 'rating', 'votes', 'genres']

# Read the TSV file with tab separator and custom column names
df_movies = pd.read_csv(
    'movie_titles_metadata.tsv',
    sep='\t',  # Tab separator for TSV files
    names=column_names  # Custom column names
)

# Display the DataFrame
df_movies.head()

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

## 🔑 5. Index Column Parameter (index_col)

### 🎯 Learning Objective:
Learn to set custom index columns for better data organization and referencing.

### 📋 Key Concepts:
- **DataFrame Index**: The row labels for accessing data
- **Unique Identifiers**: Using ID columns as indices
- **Row Access**: Improved data retrieval using meaningful indices
- **Memory Efficiency**: Better performance with proper indexing

### 💡 Benefits of Custom Index:
- ✅ **Fast Lookups**: Quick row access by ID
- ✅ **Data Integrity**: Unique row identification
- ✅ **Merge Operations**: Simplified data joining
- ✅ **Intuitive Access**: Meaningful row references

### 🔧 Implementation:

In [14]:
# Setting a specific column as the DataFrame index
# The `index_col='enrollee_id'` parameter makes 'enrollee_id' the index instead of default numeric indices

print("🔑 Setting 'enrollee_id' as the DataFrame index...")

# Read CSV with custom index column
df_indexed = pd.read_csv('aug_train.csv', index_col='enrollee_id')


# Display the DataFrame with custom index
df_indexed.head()

🔑 Setting 'enrollee_id' as the DataFrame index...

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

## 📝 6. Header Parameter

### 🎯 Learning Objective:
Master header configuration to handle files with non-standard header locations.

### 📋 Key Concepts:
- **Header Rows**: Which row contains column names
- **Multi-line Headers**: Files with metadata before headers
- **Custom Headers**: Overriding default header detection
- **Header Skipping**: Ignoring irrelevant top rows

### 💡 Common Scenarios:
- **header=0**: Default - first row as headers
- **header=1**: Second row as headers (skip metadata)
- **header=None**: No headers - use default column names
- **header=[0,1]**: Multi-level headers

### 🔧 Implementation:

In [16]:
# Using header parameter to specify which row contains column names
# The `header=1` parameter tells pandas to use the second row (index 1) as column headers


# Read CSV with header in the second row (index 1)
df_custom_header = pd.read_csv('test.csv', header=1)

# Display the DataFrame
df_custom_header.head()

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

## 📊 7. Column Selection Parameter (usecols)

### 🎯 Learning Objective:
Learn to selectively load only required columns for memory efficiency and faster processing.

### 📋 Key Concepts:
- **Selective Loading**: Import only needed columns
- **Memory Optimization**: Reduce memory usage for large datasets
- **Performance**: Faster loading and processing
- **Column Specification**: By name, index, or callable function

### 💡 Benefits of Column Selection:
- ✅ **Memory Efficiency**: Load only what you need
- ✅ **Faster Processing**: Reduced data volume
- ✅ **Cleaner Analysis**: Focus on relevant features
- ✅ **Bandwidth Saving**: Less data transfer for remote files

### 🔧 Implementation:

In [17]:
# Selective column loading using usecols parameter
# Only load specific columns instead of the entire dataset

print("📊 Loading only selected columns...")

# Define the columns we want to load
selected_columns = ['enrollee_id', 'gender', 'education_level']

# Read CSV with only selected columns
df_selected = pd.read_csv('aug_train.csv', usecols=selected_columns)


# Display the DataFrame with selected columns
df_selected.head()

📊 Loading only selected columns...

   enrollee_id gender education_level
0         8949   Male        Graduate
1        29725   Male        Graduate
2        11561    NaN        Graduate
3        33241    NaN        Graduate
4          666   Male         Masters

## 📏 8. Row Limiting Parameters (skiprows/nrows)

### 🎯 Learning Objective:
Master row control parameters for efficient data sampling and large file handling.

### 📋 Key Concepts:
- **nrows**: Limit the number of rows to read
- **skiprows**: Skip specific rows from the beginning
- **Data Sampling**: Quick preview of large datasets
- **Memory Management**: Handle files larger than available RAM

### 💡 Use Cases:
- ✅ **Large File Preview**: Quick exploration without loading everything
- ✅ **Data Sampling**: Statistical analysis on subset
- ✅ **Testing Code**: Develop with small samples before full data
- ✅ **Memory Constraints**: Work within system limitations

### 🔧 Implementation:

In [ ]:
# Using nrows parameter to limit the number of rows loaded
# This is useful for quick data exploration or memory management



# Read only the first 100 rows of the dataset and skip row 0 and row 5
df_sample = pd.read_csv('aug_train.csv', skiprows=[0,5], nrows=100)


# Display basic info about the sample
print(f"Index range: {df_sample.index.min()} to {df_sample.index.max()}")
df_sample.head()

📏 Loading only the first 100 rows...
Index range: 0 to 99

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

## 🌍 10. Encoding Parameter

### 🎯 Learning Objective:
Handle different text encodings to prevent character display issues and reading errors.

### 📋 Key Concepts:
- **Text Encoding**: How characters are stored in bytes
- **UTF-8**: Universal encoding (most common)
- **Latin-1**: Western European characters
- **ASCII**: Basic English characters only
- **Encoding Errors**: Character corruption prevention

### 💡 Common Encodings:
- ✅ **utf-8**: Default, handles most languages
- ✅ **latin-1**: European languages, legacy files
- ✅ **ascii**: Basic English only
- ✅ **cp1252**: Windows encoding

### 🚨 Signs of Encoding Issues:
- Strange characters (�, ?, weird symbols)
- UnicodeDecodeError exceptions
- Missing or corrupted text

### 🔧 Implementation:

In [23]:
# Using encoding parameter to handle files with special characters
# latin-1 encoding is often needed for files with European characters

print("🌍 Reading file with latin-1 encoding...")

try:
    # Read CSV with specific encoding to handle special characters
    df_zomato = pd.read_csv('zomato.csv', encoding='latin-1')
    
    print(f"✅ File loaded successfully with latin-1 encoding!")
    print(f"📊 Dataset Shape: {df_zomato.shape}")
    print(f"📋 Columns: {df_zomato.columns.tolist()}")
    print("\n🔍 First 5 rows:")
    
    # Display the DataFrame
    df_zomato.head()
    
except UnicodeDecodeError as e:
    print(f"❌ Encoding error: {e}")
    print("💡 Try different encoding like 'utf-8', 'cp1252', or 'ascii'")
except FileNotFoundError:
    print("📁 File 'zomato.csv' not found in current directory")

🌍 Reading file with latin-1 encoding...
✅ File loaded successfully with latin-1 encoding!
📊 Dataset Shape: (9551, 21)
📋 Columns: ['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']

🔍 First 5 rows:

## 🚨 11. Error Handling - Skip Bad Lines

### 🎯 Learning Objective:
Learn to handle corrupted or malformed rows in CSV files gracefully.

### 📋 Key Concepts:
- **Data Quality Issues**: Malformed rows, inconsistent columns
- **Error Recovery**: Continue processing despite bad data
- **Data Validation**: Identify and handle problematic records
- **Robust Loading**: Prevent crashes from data issues

### 💡 Common Data Problems:
- ⚠️ **Extra Columns**: Rows with more fields than headers
- ⚠️ **Missing Columns**: Rows with fewer fields
- ⚠️ **Delimiter Issues**: Inconsistent separators
- ⚠️ **Quote Problems**: Unclosed quotes or escaping issues

### 🔧 Error Handling Options:
- **on_bad_lines='error'**: Stop and raise error (default)
- **on_bad_lines='warn'**: Show warning and skip
- **on_bad_lines='skip'**: Silently skip bad lines

### 🔧 Implementation:

In [ ]:
# Handling corrupted data with error handling
# Using on_bad_lines parameter to skip problematic rows

print("🚨 Reading file with error handling...")

try:
    # Read CSV with bad line handling (modern pandas syntax)
    # Note: error_bad_lines is deprecated, use on_bad_lines instead
    df_books = pd.read_csv(
        'BX-Books.csv', 
        sep=';', 
        encoding="latin-1",
        on_bad_lines='skip'  # Skip bad lines instead of crashing
    )
    
    print(f"✅ File loaded with error handling!")
    print(f"📊 Dataset Shape: {df_books.shape}")
    print("⚠️ Any malformed rows were automatically skipped")
    print("\n🔍 First 5 rows:")
    
    # Display the DataFrame
    df_books.head()
    
except Exception as e:
    print(f"❌ Error loading file: {e}")
    print("💡 File may not exist or have severe formatting issues")

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

## 🔢 12. Data Types Parameter (dtypes)

### 🎯 Learning Objective:
Control data types during CSV loading for memory optimization and data integrity.

### 📋 Key Concepts:
- **Type Specification**: Define column data types explicitly
- **Memory Optimization**: Choose efficient data types
- **Data Integrity**: Prevent type conversion errors
- **Performance**: Faster operations with correct types

### 💡 Common Data Types:
- **int64**: Large integers
- **int32**: Smaller integers (memory efficient)
- **float64**: Decimal numbers
- **object**: Text/mixed data
- **bool**: True/False values
- **datetime64**: Date and time data

### 🔧 Implementation:

In [24]:
# Specifying data types during CSV loading
# This ensures proper data types and can improve memory usage

print("🔢 Loading CSV with specific data types...")

# Define data types for specific columns
dtype_dict = {
    'target': int,  # Ensure target column is integer
    'enrollee_id': str,  # Keep ID as string to preserve leading zeros
}

# Read CSV with specified data types
df_typed = pd.read_csv('aug_train.csv', dtype=dtype_dict)
# Display DataFrame info showing data types
df_typed.info()

🔢 Loading CSV with specific data types...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  object
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int32
dtypes: float64(1), int32(1), int64(1), object(11)
memory usage: 2.0+ MB

## 📅 13. Date Parsing

### 🎯 Learning Objective:
Master automatic date parsing to work with temporal data effectively.

### 📋 Key Concepts:
- **Date Recognition**: Automatic detection of date formats
- **datetime64 Type**: pandas' optimized date data type
- **Time Series Analysis**: Enable time-based operations
- **Date Operations**: Filtering, grouping, and analysis by dates

### 💡 Benefits of Date Parsing:
- ✅ **Time Series Operations**: Date-based filtering and analysis
- ✅ **Automatic Formatting**: Consistent date representation
- ✅ **Performance**: Optimized date operations
- ✅ **Built-in Methods**: Access to date-specific functions

### 🔧 Implementation:

In [ ]:
# Automatic date parsing during CSV loading
# parse_dates parameter converts specified columns to datetime

print("📅 Loading CSV with automatic date parsing...")

# Read CSV with automatic date parsing
df_ipl = pd.read_csv('IPL Matches 2008-2020.csv', parse_dates=['date'])


# Show info focusing on the date column
df_ipl.info()

# If your CSV has separate columns for year, month, and day (e.g., 'year', 'month', 'day'),
# you can combine them into a single datetime column using parse_dates with a nested list:
# Example:
# df = pd.read_csv('file.csv', parse_dates=[['year', 'month', 'day']])
# This will create a new column 'year_month_day' as datetime64[ns].

📅 Loading CSV with automatic date parsing...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

## 🔄 14. Data Converters

### 🎯 Learning Objective:
Apply custom transformation functions to columns during CSV loading.

### 📋 Key Concepts:
- **Custom Functions**: User-defined data transformations
- **Real-time Processing**: Transform data during loading
- **Data Standardization**: Normalize values on import
- **Efficiency**: Single-pass data transformation

### 💡 Use Cases:
- ✅ **Name Standardization**: Normalize company/team names
- ✅ **Data Cleaning**: Fix formatting issues during import
- ✅ **Unit Conversion**: Convert measurements automatically
- ✅ **Category Mapping**: Transform categorical values

### 🔧 Implementation:

In [26]:
def rename(name):
    if name=="Royal Challengers Bangalore":
        return "RCB"
    else:
        name

pd.read_csv('IPL Matches 2008-2020.CSV', converters={'team1': rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,None,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,None,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,None,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,None,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,None,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,None,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,None,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

## ❌ 15. Custom Missing Values (na_values)

### 🎯 Learning Objective:
Define custom values to be treated as missing/null during data loading.

### 📋 Key Concepts:
- **Missing Data Identification**: Custom null value recognition
- **Data Quality**: Proper handling of various null representations
- **Standardization**: Consistent missing value treatment
- **Domain Knowledge**: Business-specific null indicators

### 💡 Common Missing Value Indicators:
- ✅ **Standard**: NaN, None, null, NULL
- ✅ **Custom**: "N/A", "Unknown", "Missing"
- ✅ **Placeholders**: -999, 0, "TBD"
- ✅ **Domain-specific**: "Not Applicable", "Refused"

### 🔧 Implementation:

In [ ]:
# Define custom values to be treated as missing/null
# This is useful when your data uses non-standard null indicators

print("❌ Loading CSV with custom missing value indicators...")

# Define custom values that should be treated as NaN
custom_na_values = ['Male', 'Unknown', 'Not Specified', 'N/A']

# Read CSV treating custom values as missing
df_custom_na = pd.read_csv('aug_train.csv', na_values=custom_na_values)


# Check the effect on a specific column (if 'gender' exists)
if 'gender' in df_custom_na.columns:
    print(f"\n🔍 Gender column after custom NA treatment:")
    print(f"Value counts:\n{df_custom_na['gender'].value_counts(dropna=False)}")
    print(f"Missing values: {df_custom_na['gender'].isna().sum()}")
else:
    print("Gender column not found - showing general missing value info")
    
# Show overall missing value summary
print(f"\n📊 Missing values per column:")
missing_summary = df_custom_na.isnull().sum()
print(missing_summary[missing_summary > 0])  # Show only columns with missing values

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 🔄 16. Chunked Reading for Large Datasets

### 🎯 Learning Objective:
Process large datasets efficiently using chunk-based reading for memory management.

### 📋 Key Concepts:
- **Memory Management**: Handle files larger than available RAM
- **Chunk Processing**: Read data in manageable pieces
- **Iterative Analysis**: Process data batch by batch
- **Scalability**: Handle any file size regardless of memory

### 💡 When to Use Chunked Reading:
- ✅ **Large Files**: Files too big for memory
- ✅ **Limited RAM**: Working with memory constraints
- ✅ **Streaming Analysis**: Real-time data processing
- ✅ **Batch Operations**: Process data in segments

### 🔧 Implementation:

In [ ]:
# Create a chunk reader for large dataset processing
# chunksize parameter returns an iterator instead of loading all data at once

print("🔄 Setting up chunked reading for large dataset...")

# Create a chunk reader with specified chunk size
chunk_size = 5000
chunk_reader = pd.read_csv('aug_train.csv', chunksize=chunk_size)

print(f"✅ Chunk reader created!")
print(f"📦 Chunk size: {chunk_size} rows")
print(f"🔄 Reader type: {type(chunk_reader)}")
print("\n💡 This creates an iterator - no data loaded yet!")
print("Use the iterator in a loop to process chunks one by one.")

In [ ]:
# Process chunks iteratively for memory-efficient analysis
# This demonstrates how to work with chunked data

print("🔄 Processing chunks iteratively...")

# Recreate chunk reader (iterators can only be used once)
chunk_reader = pd.read_csv('aug_train.csv', chunksize=5000)

chunk_count = 0
total_rows = 0

# Process each chunk
for chunk in chunk_reader:
    chunk_count += 1
    total_rows += len(chunk)
    
    print(f"📦 Chunk {chunk_count}: Shape {chunk.shape}")
    
    # Example analysis on each chunk
    if 'gender' in chunk.columns:
        print(f"   Gender distribution: {chunk['gender'].value_counts().to_dict()}")
    
    # Limit output for demonstration
    if chunk_count >= 3:  # Process only first 3 chunks for demo
        print("   ... (stopping after 3 chunks for demonstration)")
        break

print(f"\n✅ Processed {chunk_count} chunks")
print(f"📊 Total rows processed: {total_rows}")
print("💡 This approach allows processing datasets of any size!")

(4158, 14)
(4158, 14)
(4158, 14)
(4158, 14)